### PR TITLE
Supporting Apple silicon hardware with arm64-darwin-22 platform

### PR DESCRIPTION
**Pull request by timgentry**

### CODE REVIEW

**Review by ollietulloch — DISMISSED** [review]

**Comment by bshand** [comment]
@timgentry Do all tests pass for you? I get the follow 4 failures in the `feature/apple_silicon_support` branch of your fork, but no failures in the `develop` branch:

```
$ (rails test test/integration/contracts_test.rb:109;
rails test test/integration/data_privacy_impact_assessments_test.rb:121;
rails test test/integration/reports_test.rb:29;
rails test test/integration/reports_test.rb:9)
Run options: --seed 3604

# Running:

    HTML screenshot: /Users/brian/mbis_tim/tmp/screenshots/screenshot_2023-04-20-09-46-53.455.html
    Image screenshot: /Users/brian/mbis_tim/tmp/screenshots/screenshot_2023-04-20-09-46-53.455.png
E

Error:
ContractsTest#test_should_be_able_to_download_attached_document:
RuntimeError: Waited 10 for download, without success!
    test/download_helpers.rb:55:in `wait_for_download'
    test/integration/contracts_test.rb:123:in `block in <class:ContractsTest>'


rails test test/integration/contracts_test.rb:109



Finished in 29.972657s, 0.0334 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
mbis_tim $ rails test test/integration/data_privacy_impact_assessments_test.rb:121;
Run options: --seed 12999

# Running:

    HTML screenshot: /Users/brian/mbis_tim/tmp/screenshots/screenshot_2023-04-20-09-47-29.372.html
    Image screenshot: /Users/brian/mbis_tim/tmp/screenshots/screenshot_2023-04-20-09-47-29.372.png
E

Error:
DataPrivacyImpactAssessmentsTest#test_should_be_able_to_download_attached_document:
RuntimeError: Waited 10 for download, without success!
    test/download_helpers.rb:55:in `wait_for_download'
    test/integration/data_privacy_impact_assessments_test.rb:135:in `block in <class:DataPrivacyImpactAssessmentsTest>'


rails test test/integration/data_privacy_impact_assessments_test.rb:121



Finished in 27.272903s, 0.0367 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
mbis_tim $ rails test test/integration/reports_test.rb:29;
Run options: --seed 47422

# Running:

    HTML screenshot: /Users/brian/mbis_tim/tmp/screenshots/screenshot_2023-04-20-09-48-04.379.html
    Image screenshot: /Users/brian/mbis_tim/tmp/screenshots/screenshot_2023-04-20-09-48-04.379.png
E

Error:
ReportsTest#test_user_can_download_report_they_have_been_granted_access_to:
RuntimeError: Waited 10 for download, without success!
    test/download_helpers.rb:55:in `wait_for_download'
    test/integration/reports_test.rb:41:in `block (2 levels) in <class:ReportsTest>'
    test/integration/reports_test.rb:35:in `block in <class:ReportsTest>'


rails test test/integration/reports_test.rb:29



Finished in 26.178162s, 0.0382 runs/s, 0.0382 assertions/s.
1 runs, 1 assertions, 0 failures, 1 errors, 0 skips
mbis_tim $ rails test test/integration/reports_test.rb:9
Run options: --seed 8665

# Running:

    HTML screenshot: /Users/brian/mbis_tim/tmp/screenshots/screenshot_2023-04-20-09-48-38.934.html
    Image screenshot: /Users/brian/mbis_tim/tmp/screenshots/screenshot_2023-04-20-09-48-38.934.png
E

Error:
ReportsTest#test_data_in_report_1_is_correct:
RuntimeError: Waited 10 for download, without success!
    test/download_helpers.rb:55:in `wait_for_download'
    test/integration/reports_test.rb:14:in `block in <class:ReportsTest>'

rails test test/integration/reports_test.rb:9

Finished in 26.663775s, 0.0375 runs/s, 0.0750 assertions/s.
1 runs, 2 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by timgentry** [comment]
@bshand I do get the errors, which is why I changed this PR to a draft. I was waiting for @ollietulloch to let me know if there were any on the `develop` branch, so thanks for the quick reply. I need to fix the breaking changes in the selenium and webdrivers version bumps before we can merge.

**Review by bshand — APPROVED** [review]
Yes, I'm happy with all this, and the test failures have been fixed upstream, so I'm happy to merge this now.

**Comment by bshand** [comment]
This has now been merged to the future home https://github.com/NHSDigital/data_management_system and the GitHub Actions tests all passed there.

**Pull request merged**
